### ISSUE TITLE
это только у меня не работает или Яндекс опять что-то поменял?

### ISSUE THREAD

**Issue by alexanderznamensky** [tayanov/Yandex-tts-speechkit-FIX#3]

**Comment by alexanderznamensky** [comment]
UPD: все работает!

при получении API key нужно было служебному аккаунту в Яндекс облаке  дать роль на редактирование )))

после этого все взлетело!

спасибо автору!

**Comment by alexanderznamensky** [comment]
После обновления до 0.115.5 компонент перестал работать.
В гугле достаточно было отключить "language: ru".

В Яндекс ТТС вот такое сообщение:
TextFrame(encoding=<Encoding.UTF8: 3>, text=['ru-RU']) needs to be str for key 'artist'.
Удаление language: 'ru-RU' ничего не дает.

**Comment by tayanov** [comment]
доброго дня. к сожалению я сам не использую этот компонент. потому не могу понять ошибку, так же не нашел никого в сообществе в телеграмме у кого имелась такая бы проблема. на на 115,6 пробовали?

**Comment by alexanderznamensky** [comment]
Добрый день. Спасибо за обратную связь!

Да, уже попробовал 0.115.6 - тоже самое.... (а на 0.115.3 - работает - пришлось откатиться).
Как я понимаю, это связано с изменениями для гугла - там появилась
мультиязычная поддержка и теперь не нужно указывать язык для ТТС.

**Comment by tayanov** [comment]
Чуть позже попробую глянуть.

**Comment by alexanderznamensky** [comment]
Большое спасибо! Если будет нужна моя посильная помощь, я с 8 вечера - в вашем распоряжении

**Comment by tayanov** [comment]
> Большое спасибо! Если будет нужна моя посильная помощь, я с 8 вечера - в вашем распоряжении

покажи конфиг. у меня обычная версия работает. а этот кастом от обычной версии мало чем отличается

**Comment by alexanderznamensky** [comment]
вот:
```
homeassistant:
  name: My Smart Home на даче
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 186
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    #language: ru
    # service_name: google_say
    # cache: true
    # cache_dir: /local/tts
    # cache_dir: /tmp/tts
    # time_memory: 300
    base_url: http://192.168.1.78:8123

# tts:
  - platform: yandextts
    language: 'ru-RU'
#    service_name: yandex_alena
    api_key: !secret YANDEX_API_KEY
    codec: oggopus
    voice: alena
    # emotion: good
    speed: 0.9

media_player:
  - platform: mpd
    host: 192.168.1.78
    name: raspberryha

yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password
  tts_service_name: alice_say

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.10.1
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.9.4
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js?v=3.0.1
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module

hacs:
   token: !secret HACS_github
   appdaemon: true
   python_script: true
   theme: true

#Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
light: !include includes/light.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/bin_sensor
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts
switch: !include_dir_merge_list includes/switches

mqtt:
# Выбрать один из вариантов для брокера!  
  broker: core-mosquitto  # Локальный брокер
#  broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant  
  username: mqtt
  password: mqtt

telegram_bot:
  - platform: polling
    api_key: !secret api_key_bot
    allowed_chat_ids:
     - !secret telegram_id_1
     - !secret telegram_id_2
     - !secret telegram_id_3

notify:
  - name: AlexanderZnamensky
    platform: telegram
    chat_id: !secret telegram_id_1
    
  - name: AlexanderZnamensky2
    platform: telegram
    chat_id: !secret telegram_id_2

  - name: ОльгаПрилепина
    platform: telegram
    chat_id: !secret telegram_id_3

google:
  client_id: !secret CLIENT_ID
  client_secret: !secret CLIENT_SECRET

morph_numbers:

```

**Comment by tayanov** [comment]
и полную ошибку если можно,
и на какой плеер выводится ттс, и откуда? из вебморды или автоматизации?
может в телегу кинешь? @tayanov

**Comment by alexanderznamensky** [comment]
Можно, конечно. Но это из дома уже - после 20.

**Comment by balonchiks** [comment]
подтверждаю - ровно такая же ошибка и на 0.115.5 у на .6
более того, в папке config/tts не появляется сгенерированный аудио фаил

вот ошибка из логов, при запуске из developer tools-> services -> tts.yandextts_say:
```
2020-10-01 16:07:22 ERROR (MainThread) 
[homeassistant.components.websocket_api.http.connection.140588446053808] TextFrame(encoding=<Encoding.UTF8: 3>, text=['ru-RU']) needs to be str for key 'artist'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 168, in async_say_handle
    url = await tts.async_get_url(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 341, in async_get_url
    filename = await self.async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 368, in async_get_tts_audio
    data = self.write_tags(filename, data, provider, message, language, options)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 474, in write_tags
    tts_file.save(data_bytes)
  File "/usr/local/lib/python3.8/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mutagen/ogg.py", line 587, in save
    self.tags._inject(filething.fileobj, padding)
  File "/usr/local/lib/python3.8/site-packages/mutagen/oggopus.py", line 122, in _inject
    vcomment_data = b"OpusTags" + self.write(framing=False)
  File "/usr/local/lib/python3.8/site-packages/mutagen/_vorbis.py", line 178, in write
    self.validate()
  File "/usr/local/lib/python3.8/site-packages/mutagen/_vorbis.py", line 158, in validate
    raise ValueError(err)
ValueError: TextFrame(encoding=<Encoding.UTF8: 3>, text=['ru-RU']) needs to be str for key 'artist'
```

если просто вводить фразу через медиаплеер в lovelace то в логах так:

`Failed to cast media ФРАЗАКОТОРУЮХОТЕЛСКАЗАТЬ. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address`

**Comment by alexanderznamensky** [comment]
А можете прислать лог своей ошибки?
Заранее спасибо!

**Comment by balonchiks** [comment]
см выше, обновил свое сообщение

**Comment by tayanov** [comment]
Ну у меня и ключа нет. Если кто доверяет. И даст на тест в личку, могу поковырять.

**Comment by tayanov** [comment]
Почему 'artist' не пойму?

**Comment by alexanderznamensky** [comment]
конечно. давайте личку или телеграм.

```
Уровень: ERROR
Logger: homeassistant.components.websocket_api.http.connection.1739067624
Source: components/tts/__init__.py:474
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:52:43 (1 occurrences)
Last logged: 20:52:43

TextFrame(encoding=<Encoding.UTF8: 3>, text=['ru-RU']) needs to be str for key 'artist'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 168, in async_say_handle
    url = await tts.async_get_url(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 341, in async_get_url
    filename = await self.async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 368, in async_get_tts_audio
    data = self.write_tags(filename, data, provider, message, language, options)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 474, in write_tags
    tts_file.save(data_bytes)
  File "/usr/local/lib/python3.8/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mutagen/ogg.py", line 587, in save
    self.tags._inject(filething.fileobj, padding)
  File "/usr/local/lib/python3.8/site-packages/mutagen/oggopus.py", line 122, in _inject
    vcomment_data = b"OpusTags" + self.write(framing=False)
  File "/usr/local/lib/python3.8/site-packages/mutagen/_vorbis.py", line 178, in write
    self.validate()
  File "/usr/local/lib/python3.8/site-packages/mutagen/_vorbis.py", line 158, in validate
    raise ValueError(err)
ValueError: TextFrame(encoding=<Encoding.UTF8: 3>, text=['ru-RU']) needs to be str for key 'artist'
Не удалось вызвать службу tts/yandextts_say. TextFrame(encoding=<Encoding.UTF8: 3>, text=['ru-RU']) needs to be str for key 'artist'

```

**Comment by alexanderznamensky** [comment]
вывод на mpd плеер (он, кстати, старые файлы из кеша воспроизводит, которые на 0.115.3 были созданы):
media_player:
  - platform: mpd
    host: 192.168.1.78
    name: raspberryha
А из веб-морды через mini-media-player проигрываю и через скрипты и через автоматизацию. Разницы никакой нет.
Меня тоже ключ "артист" повеселил )))

**Comment by balonchiks** [comment]
потестировал еще немного. откатился на версию 0.115.3 - работает, но только через developer tools-> services -> tts.yandextts_say

при попытке сказать что-то через карточку медиа плеера попрежнему 

`Failed to cast media ФРАЗАКОТОРУЮХОТЕЛСКАЗАТЬ. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address`

при этом и internal_url и external_url в настройках установлены

похоже чтото именно в .115.4 они поломали со своими медиа плеерами. помоему они компонент cast как раз в .115.4 обновили

похоже что [вот это](https://github.com/home-assistant/core/commit/52b745b8a9d477eb2a5583840dcc19dabc2b0fdf#) может быть местом где все ломается?

**Comment by alexanderznamensky** [comment]
у меня на 0.115.3 все работает, как надо.
но у меня установлен mini-media-pleyar с такими параметрами:
```
          - entity: media_player.raspberryha
            type: 'custom:mini-media-player'
            artwork: full-cover
            tts:
              platform: yandextts
              language: 'ru-RU'
```
да, и в конфиге пришлось убрать service_name:
```
tts:
  - platform: yandextts
    language: 'ru-RU'
#    service_name: yandex_alena
    api_key: !secret YANDEX_API_KEY
    codec: oggopus
    voice: alena
    # emotion: good
    speed: 0.9


```
в скриптах и в автоматизации тоже работает:
```
time_yandex_tts:
      alias: 'Yandex Время'
      sequence:
      - service: tts.yandextts_say
        data:
          entity_id: media_player.raspberryha
          language: 'ru-RU'
          message: 'Московское время {{ states("sensor.time") }}'

time_google_tts:
      alias: 'Google Время'
      sequence:
      - service: tts.google_translate_say
        data:
          language: 'ru'
          entity_id: media_player.raspberryha
          message: 'Московское время {{ states("sensor.time") }}'
```

**Comment by balonchiks** [comment]
>           - entity: media_player.raspberryha
>             type: 'custom:mini-media-player'
>             artwork: full-cover
>             tts:
>               platform: yandextts
>               language: 'ru-RU'

спасибо, с разделом tts и у меня заработало и на 115.3, до этого правда год работало без него.. автоматизации тоже работают

**Comment by alexanderznamensky** [comment]
))) может постепенно вместе победим ее?

**Comment by balonchiks** [comment]
мне удалось заставить работать компонент на последней версии homeassistant. как я и предпологал, проблема в том, что ID3 данные в аудиофаиле [начиная с версии 0.115.4](https://github.com/home-assistant/core/commit/52b745b8a9d477eb2a5583840dcc19dabc2b0fdf#) ковертируются в TextFrame, и, видимо в аудиофайле с речью от yandextts чтото не так, и конвертация ломается. оталось понять что не так, и как исправить.

чтобы компонент работал на версии 0.115.4 и новее надо вернуть назад старую версию компонента tts. для этого надо скачать zip архив версии [0.115.3](https://github.com/home-assistant/core/releases/tag/0.115.3) и папку `tts` которая лежит в `homeassistant/components`, положить себе по пути `/config/custom_components` и перезагрузить homeassistant.

**_edit_**: так же возможно придется исправить `__init__.py` в `/config/custom_components/tts` и заменить эту строчку:

`tts_file = mutagen.File(data_bytes, easy=True)`

на вот эту:

`tts_file = mutagen.File(data_bytes)`

еще заметил, что у меня несколько tts в конфиге (yandextts и alice_say), и, по идее, в lovelace для медиа плееров должен был использоватся первый по алфавиту, то есть alice_say, однако все время использовался yandextts. начиная с версии 0.115.4 по умолчанию используется alice_say, который работает только с колонками yandex, поэтому пришлось переименовать alice_say в z_alice_say чтоб по умолчанию использовался yandextts.

**Comment by balonchiks** [comment]
оказывается есть еще более простой способ, при котором не потребуется никаких  замен в `/config/custom_components/tts`

надо просто указать `codec: lpcm` в configuration.yaml для вашего tts.

теперь точно понятно, что проблема в том что tts яндекса используетс кодек oggopus, и именно это и ломает всю интеграцию. проблема не в компоненте, а в TextFrame который используется в homeassistant начиная с версии 0.115.4

**Comment by tayanov** [comment]
Вот и отлично)

**Comment by alexanderznamensky** [comment]
Большое всем спасибо!

**Comment by alexanderznamensky** [comment]
> оказывается есть еще более простой способ, при котором не потребуется никаких замен в `/config/custom_components/tts`
> 
> надо просто указать `codec: lpcm` в configuration.yaml для вашего tts.
> 
> теперь точно понятно, что проблема в том что tts яндекса используетс кодек oggopus, и именно это и ломает всю интеграцию. проблема не в компоненте, а в TextFrame который используется в homeassistant начиная с версии 0.115.4

странно.... после вышеуказанных действий ошибка пропала, но mpd через mini-meda-plyaer похоже не может воспроизвести lpcm формат.....

**Comment by balonchiks** [comment]
да, простите, погорячился, точно работает только первый метод, второй работает в бете 0.116.b2 и дальше. 7 числа должна выйти финальная 0.116.0 и там будут работать оба способа

**Comment by alexanderznamensky** [comment]
ясно, спасибо. Оба, имеется ввиду и lpcm и oggopus?

**Comment by balonchiks** [comment]
нет, я имел ввиду что тот первый вариант с подменой папки `tts `и вариант с lpcm. когда будет работать опция с oggopus - незнаю, я открыл [issue](https://github.com/home-assistant/core/issues/41041), но пока никакой реакции нет

**Comment by balonchiks** [comment]
судя по всему проблема решена и все будет починено в 0.116 [этим коммитом](https://github.com/home-assistant/core/pull/41191)

**Comment by alexanderznamensky** [comment]
все верно - с 0.116 все работает - починили. кодек oggopus тоже работает.
